local utils = require 'b4mbus.utils.utils'

utils.set_vim_options {
  splitright = true,
  splitbelow = true,
  shiftround = true,
  hlsearch = false,
  cursorline = false,
  swapfile = false,
  undofile = true,
  expandtab = false,
  lazyredraw = false,
  relativenumber = true,
  number = true,
  list = true,
  incsearch = true,
  termguicolors = true,
  autoread = true,
  pumheight = 10,
  ignorecase = true,
  smartcase = true,
  showmode = false,
  foldcolumn = '1',
  foldenable = true,
  foldmethod = 'expr',
  foldlevel = 99,
  foldlevelstart = 99,
  foldexpr = 'nvim_treesitter#foldexpr()',
  wildmenu = true,
  cole = 2,
  updatetime = 50,
  shiftwidth = 2,
  scrolloff = 999,
  sidescrolloff = 8,
  tabstop = 2,
  timeoutlen = 350,
  laststatus = 3,
  history = 10000,
  cmdheight = 0,
  signcolumn = 'yes',
  grepprg = 'rg -n $* /dev/null',
  clipboard = 'unnamedplus',
  mouse = 'a',
  inccommand = 'nosplit',
  listchars = {
    tab = '> ',
    lead = '·',
    trail = '•',
    nbsp = '␣',
    precedes = '«',
    extends = '»'
  },
  fillchars = {
    stl = ' ',
    stlnc = ' ',
    diff = '╱',
    fold = ' ',
    foldsep = ' ',
    foldclose = '',
    foldopen = '',
    eob = ' ',
    msgsep = '─'
  },
  diffopt = {
    algorithm = 'histogram',
    internal = true,
    ['indent-heuristic'] = true,
    filler = true,
    closeoff = true,
    iwhite = true,
    vertical = true
  },
  showbreak = "⤷ ",
  selection = 'old',
  completeopt = { 'menu' ,'menuone' ,'noselect' },
  wildoptions = function(wo)
    return wo:remove('pum')
  end,
}

vim.cmd[[ set formatoptions-=cro ]]
