local utils = require 'config.utils.utils'

utils.set_vim_options {
	splitright = true,
	splitbelow = true,
	shiftround = true,
	hlsearch = true,
	cursorline = true,
	swapfile = false,
	undofile = true,
	expandtab = false,
	lazyredraw = true,
	relativenumber = true,
	number = true,
	list = true,
	incsearch = true,
	termguicolors = true,
	autoread = true,
	shiftwidth = 2,
	scrolloff = 5,
	sidescrolloff = 5,
	tabstop = 2,
	timeoutlen = 350,
	laststatus = 3,
	sh = 'nu',
	clipboard = 'unnamedplus',
	mouse = 'a',
	inccommand = 'split',
	guifont = 'JetBrainsMono Nerd Font Mono',
	listchars = 'eol:↴,nbsp:+,tab:> ,trail:-',
	selection = 'old',
	completeopt = {'menu' ,'menuone' ,'noselect'},
}
